[package]
name = "embedded-test-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.9", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.6"
cortex-m-semihosting = "0.6.0"
embedded-alloc = "0.7.0"

[features]
default = ["ram-64k"]
ram-64k = []
ram-16k = []
